[project]
name = "dd-manager"
version = "0.1.2"
description = "HardClone CLI & GUI disk cloner"
dependencies = [
    "PyQt5",
    "psutil",
    "rich"
]
requires-python = ">=3.10"

[project.scripts]
hardclone = "dd_manager.cli.main_cli:main"
hardclone-gui = "dd_manager.gui.main_gui:main"
